import tiktoken


class TiktokenWrapper:
    """
    A wrapper class for the Tiktoken tokenizer.

    Args:
        model (str): The name of the model to use for tokenization. Defaults to 'gpt-4'.

    Attributes:
        tokenizer: The Tiktoken tokenizer object.

    Methods:
        tokenize: Tokenizes the input string using the Tiktoken tokenizer.

    """

    def __init__(self, model="gpt-4") -> None:
        self.tokenizer = tiktoken.encoding_for_model("gpt-4")

    def tokenize(self, target: str) -> list:
        """
        Tokenizes the input string using the Tiktoken tokenizer.

        Args:
            target (str): The input string to tokenize.

        Returns:
            list: The list of tokens generated by the tokenizer.

        """
        return self.tokenizer.encode(target)
